### ISSUE TITLE
error : Error: Cannot read property 'nodeName' of undefined.

### ISSUE THREAD

**Issue by tejas-namjoshi** [tsayen/dom-to-image#109]
I have a react component.I am trying to render that component and then get the png dataurl of that component.When i run it inside a browser like chrome,  it works just fine.But i want to do 
the same thing in nodejs using js-dom.
I am getting an error :  [Error: Cannot read property 'nodeName' of undefined.].
Can someone guide me what am I doing wrong.
Thanks in advance

### Library version
2.5.2

### Browsers

- [ ] Chrome 49+  
- [ ] Firefox 45+

**Comment by tsayen** [comment]
Hi it's hard to tell what you're doing wrong. It seems to me that the error
is not thrown from this lib code (I cannot find any code calling "nodeName"
property of anything in the lib source). Can you provide a full stacktrace?
Or event better, a minimal project that illustrates the problem?

**Comment by tejas-namjoshi** [comment]
Thank you for replying so quickly.
I have used this sample code block . 
domtoimage.toPng(node)
                        .then(function (dataUrl) {
                            png = dataUrl
                        })
                        .catch(function (error) {
                            console.error('oops, something went wrong!', error);
                        });

oops, something went wrong!  [Error: Cannot read property 'nodeName' of undefined.].
I am getting the error in catch.So it must be from this library I think.

**Comment by tsayen** [comment]
I understand, but that's not what I'm asking you about. Can you please
provide the error stacktrace so I can see what call causes the error?

**Comment by tejas-namjoshi** [comment]
Here is the stack trace : --

 TypeError: Cannot read property 'nodeName' of undefined
    at nodeTreeToXHTML (.../node_modules/xmlserializer/xmlserializer.js:108:17)
    at new serializeToString (../node_modules/xmlserializer/xmlserializer.js:126:44)
    at .../node_modules/dom-to-image/src/dom-to-image.js:306:24
    at process._tickCallback (node.js:438:9)

**Comment by tsayen** [comment]
looks like something is not OK with the XmlSerializer that you have in NodeJS, or with the DOM that gets passed to it in [this line](https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L306)  

You've mentioned that you're using js-dom. I've never used it myself actually, but in order to check that it is not a problem you could try to write code like that

```javascript
var node = ... // get the DOM node
var clone = node.cloneNode(true);
var serializer = new XMLSerializer();
var xml = serializer.serialize(clone);
console.log(xml);
```
if that code passes fine in your setup (with js-dom and stuff), then it's probably a problem with this lib's code

**Comment by linayin** [comment]
Uncaught TypeError: node.cloneNode is not a function
i do it as you said,it still show the error

**Comment by kwuite** [comment]
@tsayen I have the exact same issue and followed your last post

```
var node = ... // get the DOM node
var clone = node.cloneNode(true);
```

executing the above gives me the following debugger error:`
Uncaught TypeError: node.cloneNode is not a function
    at <anonymous>:1:18
(anonymous) @ VM3317:1`

So no matter which of your examples I use, I keep getting an error like `cK5hXwCepJg3DEL9h:225 Uncaught (in promise) TypeError: node.cloneNode is not a function
    at makeNodeCopy (cK5hXwCepJg3DEL9h:225)....`

Would one of my prior loaded modules be able to cause this? I am running on the meteor nodejs framework.

Thanks in advance for any advice and support.

Cince Sera,

Kelvin

**Comment by kwuite** [comment]
Got it:

The difference is that I only used classNames in my html so I catched my node by:

```var node = document.getElementsByClassName(<node_class>)```

by adding an ID to my div and then using the following line of code, I had no more problems:

```var node = document.getElementById(<node_id>);```

As described in the manual, use `getElementById`.
